openapi: 3.1.0
info:
  version: 1.0.1
  title: API first course on Udemy
  termsOfService: https://example.com/terms/
  contact:
    name: Contact our support
    email: rsouza01@gmail.com
    url: http://example.com/contact
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  x-logo:
    url: 'https://redocly.github.io/openapi-template/logo.png'
    altText: OpenAPI example logo
  description: >
    # Introduction

    API first course on Udemy

externalDocs:
  description: "Find out how to create a GitHub repo for your OpenAPI definition."
  url: 'https://github.com/Redocly/create-openapi-repo'
tags:
  - name: Customer
    description: "Example actions on customer accounts."
  - name: Products
    description: Product operations 
  - name: Order
    description: Operations about orders.    
  # - name: Admin
  #   description: "Example operations reserved for administrators."
  # - name: Info
  #   description: "Example operations for retrieving information."
  # - name: Tag
  #   description: "This is a tag description."
# x-tagGroups:
#   - name: General
#     tags:
#       - User
#       - Info
#       - Echo
#   - name: Administration
#     tags:
#       - Admin
servers:
  - url: https://{tenant}/api/v1
    variables:
      tenant:
        default: www
        description: Your tenant id
  - url: https://example.com/api/v1
paths:
  '/v1/customers':
    $ref: paths/v1/customers.yaml
  '/v1/customers/{customerId}':
    $ref: paths/v1/customers_customerId.yaml

  '/v1/products':
    $ref: paths/v1/products.yaml
  '/v1/products/{productId}':
    $ref: paths/v1/products_productId.yaml

  '/v1/orders':
    $ref: paths/v1/orders.yaml
  '/v1/orders/{orderId}':
    $ref: paths/v1/orders_orderId.yaml
      
      
  # '/users/{username}':
  #   $ref: 'paths/users_{username}.yaml'
  # '/user':
  #   $ref: 'paths/user.yaml'
  # '/user/list':
  #   $ref: 'paths/user-status.yaml'
  # /pathItem:
  #   $ref: paths/pathItem.yaml
  # /pathItemWithExamples:
  #   $ref: paths/pathItemWithExamples.yaml
  # '/echo':
  #   $ref: 'paths/echo.yaml'
security: 
  -  basic_auth: []
components:
  securitySchemes:
    main_auth:
      description: "Example description text of the OAuth2 scheme."
      type: oauth2
      flows:
        implicit:
          authorizationUrl: http://example.com/api/oauth/dialog
          scopes:
            'read:users': read user info
            'write:users': modify or remove users
    api_key:
      description: "Example description text of the API key scheme."
      type: apiKey
      in: header
      name: api_key
    basic_auth:
      type: http
      scheme: basic
# webhooks:
#   userInfo:
#     post:
#       summary: New user webhook
#       description: "Information about a new user in the system."
#       operationId: userInfo
#       tags:
#         - Info
#       requestBody:
#         content:
#           application/json:
#             schema:
#               $ref: 'components/schemas/User.yaml'
#       responses:
#         '200':
#           description: "Successfully retrieved information about a new user."
#       security:
#         - api_key: []
